services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "9200:3306"
    volumes:
      - curso-mysql:/var/lib/mysql

volumes:
  curso-mysql:
