post http://localhost:3000/course
content-type: application/json

{
    "title": "Microservicios con NestJS y Pulumi3"
}

###
put http://localhost:3000/course/064e691e-1267-4959-9c93-5b57ce8bb708
content-type: application/json

{
    "status": "published"
}

###
get http://localhost:3000/course

###
delete http://localhost:3000/course/fb36b02d-2382-4e19-82f7-f3768ba5dfb0

###
get http://localhost:3000/course/26f23a71-a38b-4bf0-a344-198c21255abe

###
get http://localhost:3000/course/page/2/size/1
